####################################################################################################
# Grenn-Ampt model parameters
Ksat: 117.8   
n: 0.437   
0e: 0.417   
Wf: 49.5   
Wa: 121  
b: 4.05     
# Time variation of the parameters
var_t: 0.5
var_t_dossel: 0.5
####################################################################################################
# Interception model parameters
Cd: 0.969 # adm
Sc: 1.049 # mm
Emed: 0.332 # mm/h
Rmed: 7.13 # mm/h
n_intercept: 0.001
p: 0.031
St: 0.062
pt: 0.012
Ds: 0.120 #mm/hr
bR: 3.696

####################################################################################################
# key_value: 0.2
# Ksup: 55
# Ksub: 100
# Kperc: 70
# Kbase: 5500
# initial_soil_water: 0
# initial_rsub_water: 2
# area_bacia_km: 6.46
# area_bacia_m2: 6460000


####################################################################################################
# key_value: 0.2
# Ksup: 55
# Ksub: 100
# Kperc: 70
# Kbase: 12000
# initial_soil_water: 0
# initial_rsub_water: 2
# area_bacia_km: 6.46
# area_bacia_m2: 6460000
####################################################################################################
# key_value: 0.592335
# Ksup: 173.612
# Ksub: 226.88
# Kperc: 244.338
# Kbase: 5734.57
# initial_soil_water: 0
# initial_rsub_water: 2
# area_bacia_km: 6.46
# area_bacia_m2: 6460000
# ####################################################################################################
key_value: 0.42
Ksup: 11
Ksub: 215
Kperc: 28
Kbase: 6933
initial_soil_water: 0
initial_rsub_water: 2
area_bacia_km: 6.46
area_bacia_m2: 6460000
# # ####################################################################################################









# ####################################################################################################
# # Grenn-Ampt model parameters
# Ksat: 117.8   
# n: 0.437   
# 0e: 0.417   
# Wf: 49.5   
# Wa: 121  
# b: 4.05     
# # Time variation of the parameters
# var_t: 0.5
# var_t_dossel: 1
# ####################################################################################################
# # Interception model parameters
# Cd: 0.969 # adm
# Sc: 4 # mm
# Emed: 0.6 # mm/h
# Rmed: 7.13 # mm/h
# n_intercept: 0.001
# p: 0.031
# St: 0.062
# pt: 0.012
# Ds: 0.120 #mm/hr
# bR: 3.696
# ####################################################################################################